### ISSUE TITLE
Feature request: headers

### ISSUE THREAD

**Issue by fkulik** [DavideBelsole/great_list_view#14]
Hi, 
it would be cool to have possibility of adding header to the list which wouldn't be taken into consideration while list is dispatching its animations (it would keep its position on the top no matter what is happenning with the rest of the data)

**Comment by DavideBelsole** [comment]
Just use a CustomScrollView with a SliverList (your header) and an AnimatedSliverList (see ReadMe).

**Comment by mregnauld** [comment]
Agree with @fkulik : just adding two attributes, `header` and `footer`, for the `AutomaticAnimatedListView` would be very helpful, and much easier to implement.
Those attributes could be of type `Widget`.

Thanks.
