### ISSUE TITLE
Changing an attribute of an item not working

### ISSUE THREAD

**Issue by mregnauld** [DavideBelsole/great_list_view#17]
After reading your ReadMe, I tried the Example 5.
In that example, there is the following, which works fine:

```Dart
void swapList() {
    setState(() {
      if (dispatcher.currentList == listA) {
        dispatcher.dispatchNewList(listB);
      } else {
        dispatcher.dispatchNewList(listA);
      }
    });
  }
```

OK, now let's say that I want to just change the value of the color of one item in the list, so here is what I tried:

```Dart
void swapList() {
    setState(() {
      dispatcher.currentList[0] = ItemData(1, Colors.black);
      dispatcher.dispatchNewList(dispatcher.currentList);
    });
  }
```

But for some reason, nothing happens: the first item of the list isn't refreshed.

After some trials and errors, I found out that I have to duplicate the list **_and_** create a new instance for the first item, like the following, to make it work:

```Dart
void swapList() {
    setState(() {
      List<ItemData> listAbis = [...dispatcher.currentList];
      listAbis[0] = ItemData(1, Colors.black);
      dispatcher.dispatchNewList(listAbis);
    });
  }
```
But why? Is this the expected behavior?

**Comment by tRuNKator** [comment]
Yes, it's expected behaviour. diffutils calculates difference between two lists, if you modify original list - nothing happens

**Comment by mregnauld** [comment]
Oh ok, it took me a while to get it, as my app had some weird behavior, but it makes sense now.
Thanks.

**Comment by tRuNKator** [comment]
> Oh ok, it took me a while to get it, as my app had some weird behavior, but it makes sense now. Thanks.

Anyway, you can dispatch update thought AnimatedListController.notifyItemChanged

**Comment by mregnauld** [comment]
ok, definitely good to know, thanks!
