### ISSUE TITLE
Crash when calling setState(() => dispatcher.dispatchNewList(...))

### ISSUE THREAD

**Issue by mregnauld** [DavideBelsole/great_list_view#18]
In my Flutter project, I use the great_list_view library, following the Example 5 in the ReadMe.

Sometimes, I need to update items, so I call:

```Dart
setState(() => dispatcher.dispatchNewList(myNewList));
```

But for some reason, I get the following error:

```
setState() callback argument returned a Future.
The setState() method on ListeTitresCleState#30d55 was called with a closure or method that returned a Future. Maybe it is marked as "async".
Instead of performing asynchronous work inside a call to setState(), first execute the work (without updating the widget state), and then synchronously update the state inside a call to setState().
```

What is really surprising is that I only get that error when I run my app in Debug Mode (not in Profile / Release Mode)!

Can I get some help on that?

Thanks.

**Comment by tRuNKator** [comment]
Hi. Just use block body
```
setState(() {
  dispatcher.dispatchNewList(myNewList);
});
```
Error thrown by framework, and doesn't related to plugin. for details just look at the setState method code

**Comment by mregnauld** [comment]
Wow!!!
I wasn't expecting that, but yeah, it works!
Thank you so much!
