### ISSUE TITLE
white background when addLongPressReorderable: true

### ISSUE THREAD

**Issue by Tarmslitaren** [DavideBelsole/great_list_view#19]
if List items have no background or have transparent backgrounds, adding the addLongPressReorderable option will introduce a white background for the list items.

example using
class Item extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
      return AnimatedContainer(
            height:  height,
            duration: const Duration(milliseconds: 500),
          decoration: const BoxDecoration(
              color: Colors.transparent,
          ),
            child: Text("hello"),
      );
}

Have I missed some option to style the reorder item widget?

in addition: When adding a reorderModel  the addLongPressReorderable flag is supurflous: the longpress functionaliy is there anyway.

**Comment by Tarmslitaren** [comment]
Found solution: setting the App theme canvasColor to transparent does the trick.

**Comment by DavideBelsole** [comment]
OK
