### ISSUE TITLE
Add itemExtent 

### ISSUE THREAD

**Issue by nt4f04uNd** [DavideBelsole/great_list_view#2]
Add itemExtent to AnimatedSliverChildBuilderDelegate and elsewhere, where it's applicable, if there are such places.

**Comment by DavideBelsole** [comment]
I'm currently working the a new version of this package, and this feature has already been included.
Please, stay tuned! It will be released shortly.

**Comment by DavideBelsole** [comment]
Please, try the itemExtent attribute present in the new version (0.1.0) of this library.
