### ISSUE TITLE
Bad dependency worker_manager: ">=4.0.2"

### ISSUE THREAD

**Issue by darkstarx** [DavideBelsole/great_list_view#23]
```
Error: Expected 6 type arguments.
../…/src/dispatcher.dart:160
          _cancelable = Executor().execute<T, T, AnimatedListDiffBaseComparator<T>,
```
You must limit the max version of dependencies. The new version of the `worker_manager` has different interface of the `Executor` than you're expecting at the moment.

Is this package still being maintained?

**Comment by darkstarx** [comment]
PR here https://github.com/DavideBelsole/great_list_view/pull/24

**Comment by DavideBelsole** [comment]
try the new version 0.2.0
