### ISSUE TITLE
Discussion: About Sticky headers

### ISSUE THREAD

**Issue by JasCodes** [DavideBelsole/great_list_view#26]
Dear @DavideBelsole 

Currently, I am using multiple AnimatedSliverList inside [flutter_sticky_header](https://pub.dev/packages/flutter_sticky_header).

I there way to animate across these slivers? I don't think it will be easy solution yeah?

Jas

**Comment by DavideBelsole** [comment]
No, it is not possible to animate across slivers, and never will be, sorry.
