### ISSUE TITLE
Feature request/Doc update request: animationDuration

### ISSUE THREAD

**Issue by AntonBartlyn** [DavideBelsole/great_list_view#29]
I was unable to find a way to alter the default animation of item appearance/disappearance, and further "repositioning". The only parameter I found was `morphDuration`. I'd expect that to influence how long it takes for the same item with different content to make the transition animation.

So if it's currently possible, it would be great to mention it in the documentation. If it's not, I think a lot of lib users would benefit from adding it.

Thanks!

**Comment by DavideBelsole** [comment]
This lib is still in alpha version, for that reason the documentation is not yet complete.
You can provide a custom animation for item appearance/disappearance by setting addFadeTransaction=false and providing a custom Widget to animate it in your item builder. You should link the AnimatedWidgetBuilderData.animation to that widget .
You can also customize the duration and curve of the animation by providing a custom animator object (see DefaultAnimatedListAnimator and AutomaticAnimatedListView.animator).
At the moment it is not possible to customize animations based on the content of the item, but I will keep this in mind for a future release.
Hope it helps.
