### ISSUE TITLE
[Feature request] Support `move` item in `AnimatedSliverList`

### ISSUE THREAD

**Issue by bahung1221** [DavideBelsole/great_list_view#6]
Hi,

I think this is a known issue because I found this line in your code:
https://github.com/DavideBelsole/great_list_view/blob/cde1a52b7665000629ddbc9298cf00e9b851b40f/lib/src/animated_list_dispatcher.dart#L255-L257

Currently, when I programmatically change the position of an item to a new position, two animations occurred:
- One for **remove** that item from the old position
- One for **insert** that item into the new position

I think it will be awesome and more convenient if the item is **moving** from the old position to the new position just like the reorderable drag behavior.

If you don't have time to implement this feature, I can help with a PR but please give me some advice and direction on this feature.

Thanks 🍻

**Comment by DavideBelsole** [comment]
Hi,
this is not a bug.
The "move" feature is not supported yet.
This package is in an alpha version. This feature will be available in the future.
Thanks
