### ISSUE TITLE
feature request: scroll to index

### ISSUE THREAD

**Issue by johnnycook** [DavideBelsole/great_list_view#9]
Hello,

do you think it would be possible to implement a scrollToIndex or initialIndex feature where I could programmatically scroll to specific index? I have a list of widgets ordered by date and I need to initially show today's widgets. I couldn't figure it out. Widgets don't have fixed size.

There are libraries capable of scrolling to index, but the itemBuilder doesn't expose the index afaik.

**Comment by DavideBelsole** [comment]
Try the new version of this library 0.1.1 (see readme paragraph Additional useful methods).
